language: python
python:
- '3.5'
- '3.6'
install:
- pip install python-coveralls tox tox-travis
- pip install -r requirements.txt
script:
- tox
after_success:
- coveralls
notifications:
  slack:
    secure: tCqOXZoXmkZQbfR0di97qAX+sUKEIYozjPs/KxcqGJe1yWucnSnuNjht4zQ6Xz+CAcd0yJEdKr90AQdFjzQk+QTFnU66BbkbKGZgfeBcFcysCFB5FR2l9+xzg9ZzgZKTlUl6FtxPrWIcUa6bPdZwkMbRIc08+c026pxSYkJT1kcKWLZi71rPkUfjacKBi+xhYtdQH7bZcfedkF91j5JTAMn2TcHnyPipY3P1MdW4l4O92BLCQElRMZEIttsPDGKrxF0+EqKNdvRQ6CSUZ90N8YFl1RzdkquFMhdfHUh+PAAFZtG9nVaXlxun1DDBHPpBZbd48a6Mp81VLgADwjaz4tZjw39BnNf5iylxcTbhhhaOAqmDDYSfLDGhaqWWJkKdkdmwax6ne8w3iuq4y0PVJMHa0in4GrTe1nV1y/3NRyjUiq9+SfPsi6wOxBZD/T1Gsoy2t2B0tpimQmZl8JpQZfNXTngpDdliXtASuNJqYpggj70Aupl5hh9FvpjotZO0unU9ilPkk7GD31yATQnFZtvxgUaQOR0GKihzpr6MlZUV7179dSFoczW1es30MgoYOyal2R4QuHm+/36rP9iqWbUU0yiGnmy3329nQBRTwmoT9nERGLhm7NNf61pdfT0vwAgLmjmw93qN+FD7K7xYUKtCxW991+YPOxLcYf1Hb+A=
