language: python
python:
- '3.5'
- '3.6'
env:
  - PYTHONPATH = ['/home/travis/build/m4k5/cardschooli/cardschooli', '/home/travis/build/m4k5/cardschooli', '/home/travis/virtualenv/python3.5.5/bin', '/home/travis/virtualenv/python3.5.5/lib/python35.zip', '/home/travis/virtualenv/python3.5.5/lib/python3.5', '/home/travis/virtualenv/python3.5.5/lib/python3.5/plat-linux', '/home/travis/virtualenv/python3.5.5/lib/python3.5/lib-dynload', '/opt/python/3.5.5/lib/python3.5', '/opt/python/3.5.5/lib/python3.5/plat-linux', '/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages']
install:
  - pip install python-coveralls coverage
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - coveralls
