language: python
python:
- '3.5'
- '3.6'
env:
  - PYTHONPATH = ['cardschooli']
install:
  - pip install python-coveralls coverage
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - coveralls
